import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import { Inter } from "next/font/google";
import "./globals.css";
import { NextAuthProvider } from "@/components/Providers";
import { Providers } from "@/components/theme-provider";
import { ModeToggle } from "@/components/mode-toggle";
import SideBar from "@/components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <NextAuthProvider>
          <Providers>
            <header> </header>
            <NavBar />
            <main>{children}</main>
            <Footer />
          </Providers>
        </NextAuthProvider>
      </body>
    </html>
  );
}
